# Generated by Django 6.0.3 on 2026-03-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_rename_data_completed_to_date_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='date_completed',
            field=models.DateTimeField(blank=True, db_column='data_completed', null=True),
        ),
    ]
